### ISSUE TITLE
Connecting the max31865

### ISSUE THREAD

**Issue by vikalar** [jamieparkinson/ESP32-MAX31865#2]
Hello Jamie,

Fantastic Library.

I have tried the example but the console output always give me the same temperature -250 independently if the max31865 is connected to the esp32 or not.

No errors are reported when the max chip is unconnected.

I don't have change neither the pins or spi number in the example.

Any help?

Thank you Very much

**Comment by jamieparkinson** [comment]
It sounds like you have a problem with your connection to the MAX31865; the errors that can be reported by this library are just those it can read from the chip. Make sure you have your SDO/MISO and SDI/MOSI connections the right way round - other than that suggestion I can't really help with hardware problems I'm afraid.
