### ISSUE TITLE
Getting invalid temperature reading from RTD 3 Wire temperature sensor

### ISSUE THREAD

**Issue by Ritesh236** [jamieparkinson/ESP32-MAX31865#8]
Hello @jamieparkinson ,

We are able to resolve compilation errors related c++ which we were facing earlier. Thanks for your kind and help support for the same.

Now, We are not getting proper values from RTD Perspective while reading with default example.

> I (191) cpu_start: App cpu up.
> I (219) cpu_start: Pro cpu start user code
> I (219) cpu_start: cpu freq: 160000000
> I (219) cpu_start: Application information:
> I (223) cpu_start: Project name:     esp32-max31865-simple-example
> I (230) cpu_start: App version:      v0.3.2-dirty
> I (235) cpu_start: Compile time:     Mar 31 2021 16:45:58
> I (241) cpu_start: ELF file SHA256:  8a4579059b2594c2...
> I (247) cpu_start: ESP-IDF:          HEAD-HASH-NOTFOUND
> I (254) heap_init: Initializing. RAM available for dynamic allocation:
> I (261) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
> I (267) heap_init: At 3FFB31B8 len 0002CE48 (179 KiB): DRAM
> I (273) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
> I (279) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
> I (286) heap_init: At 4008C4C8 len 00013B38 (78 KiB): IRAM
> I (293) spi_flash: detected chip: generic
> I (297) spi_flash: flash io: dio
> I (302) cpu_start: Starting scheduler on PRO CPU.
> I (0) cpu_start: Starting scheduler on APP CPU.
> I (312) gpio: GPIO[15]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
> I (322) Temperature: -242.02 C
> I (822) Temperature: -242.02 C
> I (1322) Temperature: -242.02 C
> I (1822) Temperature: -242.02 C
> I (2322) Temperature: -242.02 C
> I (2822) Temperature: -242.02 C
> I (3322) Temperature: -242.02 C
> I (3822) Temperature: -242.02 C
> I (4322) Temperature: -242.02 C
> I (4822) Temperature: -242.02 C
> I (5322) Temperature: -242.02 C
> I (5822) Temperature: -242.02 C
> I (6322) Temperature: -242.02 C
> I (6822) Temperature: -242.02 C
> I (7322) Temperature: -242.02 C
> I (7822) Temperature: -242.02 C
> I (8322) Temperature: -242.02 C
> I (8822) Temperature: -242.02 C
> I (9322) Temperature: -242.02 C
> I (9822) Temperature: -242.02 C
> I (10322) Temperature: -242.02 C
> I (10822) Temperature: -242.02 C
> I (11322) Temperature: -242.02 C
> I (11822) Temperature: -242.02 C
> I (12322) Temperature: -242.02 C
> I (12822) Temperature: -242.02 C
> I (13322) Temperature: -242.02 C
> I (13822) Temperature: -242.02 C
> I (14322) Temperature: -242.02 C
> I (14822) Temperature: -242.02 C
> I (15322) Temperature: -242.02 C
> I (15822) Temperature: -242.02 C
> I (16322) Temperature: -242.02 C
> I (16822) Temperature: -242.02 C
> I (17322) Temperature: -242.02 C
> I (17822) Temperature: -242.02 C
> I (18322) Temperature: -242.02 C
> I (18822) Temperature: -242.02 C
> I (19322) Temperature: -242.02 C
> I (19822) Temperature: -242.02 C
> I (20322) Temperature: -242.02 C
> I (20822) Temperature: -242.02 C
> I (21322) Temperature: -242.02 C
> I (21822) Temperature: -242.02 C
> I (22322) Temperature: -242.02 C
> I (22822) Temperature: -242.02 C
> I (23322) Temperature: -242.02 C
> I (23822) Temperature: -242.02 C
> I (24322) Temperature: -242.02 C
> I (24822) Temperature: -242.02 C
> I (25322) Temperature: -242.02 C
> I (25822) Temperature: -242.02 C
> I (26322) Temperature: -242.02 C
> I (26822) Temperature: -242.02 C
> I (27322) Temperature: -242.02 C
> I (27822) Temperature: -242.02 C
> I (28322) Temperature: -242.02 C
> I (28822) Temperature: -242.02 C
> I (29322) Temperature: -242.02 C
> I (29822) Temperature: -242.02 C
> I (30322) Temperature: -242.02 C
> I (30822) Temperature: -242.02 C
> I (31322) Temperature: -242.02 C
> I (31822) Temperature: -242.02 C
> I (32322) Temperature: -242.02 C
> I (32822) Temperature: -242.02 C
> I (33322) Temperature: -242.02 C
> I (33822) Temperature: -242.02 C
> I (34322) Temperature: -242.02 C
> I (34822) Temperature: -242.02 C
> I (35322) Temperature: -242.02 C
> I (35822) Temperature: -242.02 C
> I (36322) Temperature: -242.02 C
> I (36822) Temperature: -242.02 C
> I (37322) Temperature: -242.02 C
> I (37822) Temperature: -242.02 C
> I (38322) Temperature: -242.02 C
> I (38822) Temperature: -242.02 C
> I (39322) Temperature: -242.02 C
> I (39822) Temperature: -242.02 C
> I (40322) Temperature: -242.02 C
> I (40822) Temperature: -242.02 C
> I (41322) Temperature: -242.02 C
> I (41822) Temperature: -242.02 C
> I (42322) Temperature: -242.02 C
> I (42822) Temperature: -242.02 C
> I (43322) Temperature: -242.02 C
> I (43822) Temperature: -242.02 C
> I (44322) Temperature: -242.02 C
> I (44822) Temperature: -242.02 C
> I (45322) Temperature: -242.02 C
> I (45822) Temperature: -242.02 C
> I (46322) Temperature: -242.02 C
> I (46822) Temperature: -242.02 C
> I (47322) Temperature: -242.02 C
> I (47822) Temperature: -242.02 C
> I (48322) Temperature: -242.02 C
> I (48822) Temperature: -242.02 C
> I (49322) Temperature: -242.02 C
> I (49822) Temperature: -242.02 C
> I (50322) Temperature: -242.02 C
> I (50822) Temperature: -242.02 C
> I (51322) Temperature: -242.02 C
> I (51822) Temperature: -242.02 C
> I (52322) Temperature: -242.02 C
> I (52822) Temperature: -242.02 C
> I (53322) Temperature: -242.02 C
> I (53822) Temperature: -242.02 C
> I (54322) Temperature: -242.02 C
> I (54822) Temperature: -242.02 C
> I (55322) Temperature: -242.02 C
> I (55822) Temperature: -242.02 C
> I (56322) Temperature: -242.02 C
> I (56822) Temperature: -242.02 C
> I (57322) Temperature: -242.02 C
> I (57822) Temperature: -242.02 C
> I (58322) Temperature: -242.02 C
> I (58822) Temperature: -242.02 C
> I (59322) Temperature: -242.02 C
> I (59822) Temperature: -242.02 C
> I (60322) Temperature: -242.02 C
> I (60822) Temperature: -242.02 C
> I (61322) Temperature: -242.02 C
> I (61822) Temperature: -242.02 C
> I (62322) Temperature: -242.02 C
> I (62822) Temperature: -242.02 C
> I (63322) Temperature: -242.02 C
> I (63822) Temperature: -242.02 C
> I (64322) Temperature: -242.02 C
> I (64822) Temperature: -242.02 C
> I (65322) Temperature: -242.02 C
> I (65822) Temperature: -242.02 C
> I (66322) Temperature: -242.02 C
> I (66822) Temperature: -242.02 C
> I (67322) Temperature: -242.02 C
> I (67822) Temperature: -242.02 C
> I (68322) Temperature: -242.02 C
> I (68822) Temperature: -242.02 C
> I (69322) Temperature: -242.02 C
> I (69822) Temperature: -242.02 C
> I (70322) Temperature: -242.02 C
> I (70822) Temperature: -242.02 C
> I (71322) Temperature: -242.02 C
> I (71822) Temperature: -242.02 C
> I (72322) Temperature: -242.02 C
> I (72822) Temperature: -242.02 C
> I (73322) Temperature: -242.02 C
> I (73822) Temperature: -242.02 C
> I (74322) Temperature: -242.02 C
> I (74822) Temperature: -242.02 C
> I (75322) Temperature: -242.02 C
> I (75822) Temperature: -242.02 C
> I (76322) Temperature: -242.02 C
> I (76822) Temperature: -242.02 C
> I (77322) Temperature: -242.02 C
> I (77822) Temperature: -242.02 C
> I (78322) Temperature: -242.02 C
> I (78822) Temperature: -242.02 C
> I (79322) Temperature: -242.02 C
> I (79822) Temperature: -242.02 C
> I (80322) Temperature: -242.02 C
> I (80822) Temperature: -242.02 C
> I (81322) Temperature: -242.02 C
> I (81822) Temperature: -242.02 C
> I (82322) Temperature: -242.02 C
> I (82822) Temperature: -242.02 C
> I (83322) Temperature: -242.02 C
> I (83822) Temperature: -242.02 C
> I (84322) Temperature: -242.02 C
> I (84822) Temperature: -242.02 C
> I (85322) Temperature: -242.02 C
> I (85822) Temperature: -242.02 C
> I (86322) Temperature: -242.02 C
> I (86822) Temperature: -242.02 C
> I (87322) Temperature: -242.02 C
> I (87822) Temperature: -242.02 C
> I (88322) Temperature: -242.02 C
> I (88822) Temperature: -242.02 C
> I (89322) Temperature: -242.02 C
> I (89822) Temperature: -242.02 C
> I (90322) Temperature: -242.02 C
> I (90822) Temperature: -242.02 C
> I (91322) Temperature: -242.02 C
> I (91822) Temperature: -242.02 C
> I (92322) Temperature: -242.02 C
> I (92822) Temperature: -242.02 C
> I (93322) Temperature: -242.02 C
> I (93822) Temperature: -242.02 C
> I (94322) Temperature: -242.02 C
> I (94822) Temperature: -242.02 C
> I (95322) Temperature: -242.02 C
> I (95822) Temperature: -242.02 C
> I (96322) Temperature: -242.02 C
> I (96822) Temperature: -242.02 C
> I (97322) Temperature: -242.02 C
> I (97822) Temperature: -242.02 C
> I (98322) Temperature: -242.02 C
> I (98822) Temperature: -242.02 C
> I (99322) Temperature: -242.02 C
> I (99822) Temperature: -242.02 C
> I (100322) Temperature: -242.02 C
> I (100822) Temperature: -242.02 C
> I (101322) Temperature: -242.02 C
> I (101822) Temperature: -242.02 C
> I (102322) Temperature: -242.02 C
> I (102822) Temperature: -242.02 C
> I (103322) Temperature: -242.02 C
> I (103822) Temperature: -242.02 C
> I (104322) Temperature: -242.02 C
> I (104822) Temperature: -242.02 C
> I (105322) Temperature: -242.02 C
> I (105822) Temperature: -242.02 C
> I (106322) Temperature: -242.02 C
> I (106822) Temperature: -242.02 C
> I (107322) Temperature: -242.02 C
> I (107822) Temperature: -242.02 C
> I (108322) Temperature: -242.02 C
> I (108822) Temperature: -242.02 C
> I (109322) Temperature: -242.02 C
> I (109822) Temperature: -242.02 C

We have checked with HSPI and VSPI configuration modes but not getting any success to read temperature for the same.

Also we have checked same hardware over Arduino Board in which getting proper temperature which means that there is no any hardware issue which works fine.

can you please help if you or anyone has faced this type of issue?

Let me know if need anything else from my end.

Regards,
Ritesh Prajapati

**Comment by jamieparkinson** [comment]
Are you sure that you're using the correct pins for MISO/MOSI/CS/DRDY as per https://github.com/jamieparkinson/ESP32-MAX31865/blob/master/examples/simple/main/main.cpp#L8? This reading usually means that the microcontroller is not able to read anything from the MAX31865, ie there is a hardware/configuration issue.

**Comment by Ritesh236** [comment]
Yes. We have used same examples as you have provided link for the same.

We have only used MISO, MOSI, CS and CLK as per requirements over ESP32 Development Kit and 5V Input Supply with GND.

Also we have checked both VSPI and HSPI configurations but didn't help it.

Would you please let me know which ESP32 IDF version you have used to verify for the same?

Regards,
Ritesh Prajapati

**Comment by Ritesh236** [comment]
@jamieparkinson ,

It will be good if you can share your hardware setup at our end which will be helpful for me to move further for the same. Also it will be fine with below API or need to explicitly give HSPI_HOST like this

auto tempSensor = Max31865(12, 13, 14, 15);  ---> will this be OK?

or 

auto tempSensor = Max31865(12, 13, 14, 15, -1, HSPI_HOST);  ---> or need to explicitly give this?

Regards,
Ritesh Prajapati

**Comment by jamieparkinson** [comment]
I can't share a hardware setup with you I'm afraid, but anything like the Typical Application Circuits in the MAX31865 datasheet will work. You don't need to provide `HSPI_HOST` explicitly.

You need to make sure your pinout is correct - are your MISO, MOSI, CLK and CS definitely GPIOs 12, 13, 14 and 15, respectively? Have you got MISO/MOSI the right way round? Why are you using a 5V supply when the ESP32 and the MAX31865 are both 3V3 chips? Have you tried changing the SPI clock speed?

I'm not sure I can really help you debug a hardware issue any further I'm afraid - if there is a confirmed problem with this library then let me know.

**Comment by Ritesh236** [comment]
@jamieparkinson ,

Yes. I have double checked GPIOs 12, 13, 14 and 15 respectively as per configurations provided. Would you please let me know that in which ESP32 Device you have tested? and on which ESP32 IDF? 

We have also checked with 3.3 V Power Supply as well but getting same issue. 

We have checked on ESP32 Dev Kit C V4 with ESP32 IDF release 4.2 version. Can you please confirm that which Hardware and IDF version you have used?

Regards,
Ritesh Prajapati

**Comment by jamieparkinson** [comment]
As I remember I did this project with a no-name ESP32 dev board (that used a WROOM module) that I bought in China and with idf v4.1. I don't think either of those will be your issue, though.

**Comment by Ritesh236** [comment]
![IMG_20210401_181917](https://user-images.githubusercontent.com/33974001/113322681-9dcc6c80-9332-11eb-87b6-ff7e9fc96e1e.jpg)
Please find attached connection which we have followed. 

Also I have tried with default example over ESP32 Dev Kit C V4 but not getting any success. 

We have checked through CRO and found that we are not getting any clock and CS pins to be triggered. So I am little bit surprised that same MAX module connection is working on Arduino Board but not working on ESP32 Development Board. 

I agreed that there is no any issue with ESP32 IDF version which we are using and also ESP32 board which we are using because we have checked few other GPIO based or I2C based temperature sensor which works fine on same board. 

Let me know if you have any suggestion or feedback for the same. 

Regards, 
Ritesh Prajapati

**Comment by jamieparkinson** [comment]
I'm afraid that photo doesn't really show me anything I can help with at all. I think you will need to do some more problem-solving yourselves: please do try changing some of the SPI config inside the component and if you find a specific issue - it's entirely possible that it is a firmware bug - then please report back. I won't be able to provide any further support and so will close this issue until that time.
