### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Dharminder-10** [jamieparkinson/ESP32-MAX31865#9]
error: static assertion failed: portGET_ARGUMENT_COUNT() result does not match for 0 arguments
 _Static_assert(portGET_ARGUMENT_COUNT() == 0, "portGET_ARGUMENT_COUNT() result does not match for 0 arguments");

error: expected primary-expression before ')' token
 #define portYIELD_FROM_ISR(...) vPortEvaluateYieldFromISR(portGET_ARGUMENT_COUNT(__VA_ARGS__), ##__VA_ARGS__)
                                                                                                             ^
C:/ESP32-MAX31865-0.3.2/src/Max31865.cpp:42:5: note: in expansion of macro 'portYIELD_FROM_ISR'
     portYIELD_FROM_ISR();
     ^~~~~~~~~~~~~~~~~~

**Comment by carlosdelfino** [comment]
I have a project that was done a few months ago, I don't know how many, and it is stuck on version 4.4.4 and I need to revive it so that I can migrate it to newer versions of the idf-sdk, but when I compile it I get the same error above, I am using idf-sdk-4.4.4 and ESP32-MAX31865 v0.1.0, I even tried newer versions but the error only changes.

Could you please help me with this problem?

In version v0.3.0 I get this erro:

```
In file included from /home/carlosdelfino/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/stdio.h:35,
                 from /home/carlosdelfino/esp/esp-idf-v4.4.4/components/esp_common/include/esp_err.h:10,
                 from /home/carlosdelfino/esp/esp-idf-v4.4.4/components/driver/include/driver/spi_common.h:11,
                 from /home/carlosdelfino/workspace/T/components/esp32-max31865/include/Max31865.h:4,
                 from /home/carlosdelfino/workspace/T/components/esp32-max31865/src/Max31865.cpp:1:
/home/carlosdelfino/esp/esp-idf-v4.4.4/components/freertos/port/xtensa/include/freertos/portmacro.h:717:41: error: static assertion failed: portGET_ARGUMENT_COUNT() result does not match for 0 arguments
 _Static_assert(portGET_ARGUMENT_COUNT() == 0, "portGET_ARGUMENT_COUNT() result does not match for 0 arguments");
                                         ^
[1058/1140] Building CXX object esp-idf/firmware_tcp/CMakeFiles/__idf_firmware_tcp.dir/tcp.cpp.obj
/home/carlosdelfino/workspace/T/components/firmware_tcp/tcp.cpp: In member function 'int8_t TCP_CLIENT::connecto(const char*, uint16_t, const char*)':
/home/carlosdelfino/workspace/T/components/firmware_tcp/tcp.cpp:99:13: warning: unused variable 'x' [-Wunused-variable]
         int x = setsockopt(s, SOL_SOCKET, SO_BINDTODEVICE, itf, strlen(itf));
             ^
[1059/1140] Building C object esp-idf/firmware_cjson/CMakeFiles/__idf_firmware_cjson.dir/cJSON.c.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
```
